In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import requests 
import yfinance as yf

In [2]:
# https://codingandfun.com/retrieving-currency-pairs-from-yahoo-finance-with-python/ for research

In [3]:
start = "2021-01-02"
end = "2021-01-10"
# setting start and end dates
# start takes T-1

In [4]:
list_of_pairs = [
"EURUSD=X"
,"JPY=X"
,"GBPUSD=X"
,"AUDUSD=X"
,"NZDUSD=X"
,"CNY=X"
,"HKD=X"
,"SGD=X"
,"INR=X"
,"MXN=X"
,"PHP=X"
,"IDR=X"
,"MYR=X"
,"THB=X"
,"ZAR=X"
,"RUB=X"
]
#Creating a list of pairs 
#Pairs are taken from https://finance.yahoo.com/currencies/

In [5]:
list_of_values = []
for i in list_of_pairs:
    deneme = yf.Ticker(i)
    hist = deneme.history(start=start,end=end)
    hist["Name"] = i
    list_of_values.append(hist)
list_of_values

[                Open      High       Low     Close  Volume  Dividends  \
 Date
 2021-01-01  1.217285  1.221699  1.213499  1.218027       0          0
 2021-01-04  1.224905  1.230999  1.217137  1.225070       0          0
 2021-01-05  1.225295  1.229483  1.224995  1.225160       0          0
 2021-01-06  1.229861  1.235025  1.226693  1.230027       0          0
 2021-01-07  1.233776  1.234568  1.224665  1.234111       0          0
 2021-01-08  1.226873  1.228215  1.221493  1.227144       0          0

             Stock Splits      Name
 Date
 2021-01-01             0  EURUSD=X
 2021-01-04             0  EURUSD=X
 2021-01-05             0  EURUSD=X
 2021-01-06             0  EURUSD=X
 2021-01-07             0  EURUSD=X
 2021-01-08             0  EURUSD=X  ,
                   Open        High         Low       Close  Volume  Dividends  \
 Date
 2021-01-01  103.225998  103.250000  103.225998  103.225998       0          0
 2021-01-04  103.244003  103.244003  102.709999  103.238998       0          0
 2021-01-05  103.141998  103.180000  102.671997  103.125000       0          0
 2021-01-06  102.699997  103.431000  102.589996  102.678001       0          0
 2021-01-07  103.028000  103.950996  102.956001  103.024002       0          0
 2021-01-08  103.794998  104.078003  103.616997  103.790001       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  JPY=X
 2021-01-04             0  JPY=X
 2021-01-05             0  JPY=X
 2021-01-06             0  JPY=X
 2021-01-07             0  JPY=X
 2021-01-08             0  JPY=X  ,
                 Open      High       Low     Close  Volume  Dividends  \
 Date
 2021-01-01  1.369000  1.369000  1.366600  1.367301       0          0
 2021-01-04  1.368270  1.370379  1.354903  1.368420       0          0
 2021-01-05  1.357294  1.362583  1.355565  1.357160       0          0
 2021-01-06  1.362639  1.366979  1.354298  1.362955       0          0
 2021-01-07  1.362231  1.363382  1.354133  1.362528       0          0
 2021-01-08  1.356815  1.363178  1.354041  1.356963       0          0

             Stock Splits      Name
 Date
 2021-01-01             0  GBPUSD=X
 2021-01-04             0  GBPUSD=X
 2021-01-05             0  GBPUSD=X
 2021-01-06             0  GBPUSD=X
 2021-01-07             0  GBPUSD=X
 2021-01-08             0  GBPUSD=X  ,
                Open      High       Low     Close  Volume  Dividends  \
 Date
 2021-01-01  0.77718  0.820760  0.769823  0.770297       0          0
 2021-01-04  0.77130  0.774200  0.765660  0.771230       0          0
 2021-01-05  0.76698  0.775300  0.766289  0.767100       0          0
 2021-01-06  0.77628  0.782038  0.773431  0.776600       0          0
 2021-01-07  0.78154  0.781540  0.772770  0.781700       0          0
 2021-01-08  0.77690  0.779900  0.774140  0.776900       0          0

             Stock Splits      Name
 Date
 2021-01-01             0  AUDUSD=X
 2021-01-04             0  AUDUSD=X
 2021-01-05             0  AUDUSD=X
 2021-01-06             0  AUDUSD=X
 2021-01-07             0  AUDUSD=X
 2021-01-08             0  AUDUSD=X  ,
                 Open      High       Low     Close  Volume  Dividends  \
 Date
 2021-01-01  0.719400  0.749290  0.718300  0.718200       0          0
 2021-01-04  0.719678  0.723081  0.716420  0.719839       0          0
 2021-01-05  0.717911  0.724312  0.717412  0.717829       0          0
 2021-01-06  0.725531  0.731652  0.723741  0.725689       0          0
 2021-01-07  0.730471  0.730471  0.722669  0.730578       0          0
 2021-01-08  0.726438  0.728210  0.723050  0.726549       0          0

             Stock Splits      Name
 Date
 2021-01-01             0  NZDUSD=X
 2021-01-04             0  NZDUSD=X
 2021-01-05             0  NZDUSD=X
 2021-01-06             0  NZDUSD=X
 2021-01-07             0  NZDUSD=X
 2021-01-08             0  NZDUSD=X  ,
               Open    High     Low   Close  Volume  Dividends  Stock Splits  \
 Date
 2021-01-01  6.5317  6.5320  6.5315  6.5317       0          0             0
 2021-01-04  6.5257  6.5257  6.4578  6.5320       0          0             0
 2021-01-05  6.4605  6.4662  6.4294  6.4605       0          0             0
 2021-01-06  6.4552  6.4623  6.4437  6.4552       0          0             0
 2021-01-07  6.4607  6.4780  6.4465  6.4607       0          0             0
 2021-01-08  6.4772  6.4774  6.4538  6.4772       0          0             0

              Name
 Date
 2021-01-01  CNY=X
 2021-01-04  CNY=X
 2021-01-05  CNY=X
 2021-01-06  CNY=X
 2021-01-07  CNY=X
 2021-01-08  CNY=X  ,
                Open     High     Low    Close  Volume  Dividends  \
 Date
 2021-01-01  7.75320  7.75580  7.7507  7.75320       0          0
 2021-01-04  7.75291  7.75380  7.7518  7.75301       0          0
 2021-01-05  7.75276  7.75350  7.7522  7.75302       0          0
 2021-01-06  7.75280  7.75350  7.7517  7.75275       0          0
 2021-01-07  7.75301  7.75400  7.7518  7.75290       0          0
 2021-01-08  7.75310  7.75718  7.7523  7.75300       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  HKD=X
 2021-01-04             0  HKD=X
 2021-01-05             0  HKD=X
 2021-01-06             0  HKD=X
 2021-01-07             0  HKD=X
 2021-01-08             0  HKD=X  ,
                Open     High     Low    Close  Volume  Dividends  \
 Date
 2021-01-01  1.32130  1.32290  1.3209  1.32160       0          0
 2021-01-04  1.32051  1.32107  1.3157  1.32067       0          0
 2021-01-05  1.32030  1.32062  1.3168  1.32029       0          0
 2021-01-06  1.31762  1.32092  1.3153  1.31721       0          0
 2021-01-07  1.31745  1.32650  1.3166  1.31745       0          0
 2021-01-08  1.32460  1.32853  1.3212  1.32422       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  SGD=X
 2021-01-04             0  SGD=X
 2021-01-05             0  SGD=X
 2021-01-06             0  SGD=X
 2021-01-07             0  SGD=X
 2021-01-08             0  SGD=X  ,
                  Open       High        Low      Close  Volume  Dividends  \
 Date
 2021-01-01  73.089203  73.319801  73.025002  73.089203       0          0
 2021-01-04  73.092003  73.200996  72.798500  73.092003       0          0
 2021-01-05  73.091499  73.329803  72.963501  73.320000       0          0
 2021-01-06  73.167999  73.360001  73.040001  73.374802       0          0
 2021-01-07  73.374802  73.467003  73.063004  73.360001       0          0
 2021-01-08  73.730003  73.739799  73.196198  73.445999       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  INR=X
 2021-01-04             0  INR=X
 2021-01-05             0  INR=X
 2021-01-06             0  INR=X
 2021-01-07             0  INR=X
 2021-01-08             0  INR=X  ,
                 Open       High        Low      Close  Volume  Dividends  \
 Date
 2021-01-01  19.87450  19.874500  19.866600  19.874500       0          0
 2021-01-04  19.85375  19.943880  19.724501  19.847500       0          0
 2021-01-05  19.94175  20.097059  19.803900  19.942450       0          0
 2021-01-06  19.90510  19.987450  19.690800  19.902201       0          0
 2021-01-07  19.66246  19.938499  19.618999  19.655769       0          0
 2021-01-08  20.00070  20.052349  19.872370  20.000099       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  MXN=X
 2021-01-04             0  MXN=X
 2021-01-05             0  MXN=X
 2021-01-06             0  MXN=X
 2021-01-07             0  MXN=X
 2021-01-08             0  MXN=X  ,
                  Open       High        Low      Close  Volume  Dividends  \
 Date
 2021-01-01  48.070000  48.083000  47.895535  48.070000       0          0
 2021-01-04  48.004002  48.060001  47.884998  48.080002       0          0
 2021-01-05  48.040001  48.125000  47.912083  47.910000       0          0
 2021-01-06  48.099998  48.105000  47.922676  48.099998       0          0
 2021-01-07  48.090000  48.220001  47.920189  48.090000       0          0
 2021-01-08  48.174999  48.180000  47.946239  48.165001       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  PHP=X
 2021-01-04             0  PHP=X
 2021-01-05             0  PHP=X
 2021-01-06             0  PHP=X
 2021-01-07             0  PHP=X
 2021-01-08             0  PHP=X  ,
                     Open          High           Low         Close  Volume  \
 Date
 2021-01-01  13875.000000  14034.473633  13875.000000  13932.374023       0
 2021-01-04  13890.578125  14043.000000  13826.099609  14022.500977       0
 2021-01-05  13931.400391  13962.000000  13880.000000  13931.400391       0
 2021-01-06  13930.000000  13953.599609  13875.000000  13930.000000       0
 2021-01-07  13951.500000  14137.500000  13837.664062  13951.500000       0
 2021-01-08  14135.000000  14147.400391  13892.977539  13892.977539       0

             Dividends  Stock Splits   Name
 Date
 2021-01-01          0             0  IDR=X
 2021-01-04          0             0  IDR=X
 2021-01-05          0             0  IDR=X
 2021-01-06          0             0  IDR=X
 2021-01-07          0             0  IDR=X
 2021-01-08          0             0  IDR=X  ,
               Open   High     Low   Close  Volume  Dividends  Stock Splits  \
 Date
 2021-01-01  4.0200  4.020  4.0200  4.0200       0          0             0
 2021-01-04  4.0125  4.020  3.9930  4.0200       0          0             0
 2021-01-05  4.0130  4.020  4.0020  4.0040       0          0             0
 2021-01-06  4.0060  4.020  4.0045  4.0150       0          0             0
 2021-01-07  4.0125  4.038  4.0075  4.0080       0          0             0
 2021-01-08  4.0400  4.045  4.0280  4.0375       0          0             0

              Name
 Date
 2021-01-01  MYR=X
 2021-01-04  MYR=X
 2021-01-05  MYR=X
 2021-01-06  MYR=X
 2021-01-07  MYR=X
 2021-01-08  MYR=X  ,
                  Open    High        Low      Close  Volume  Dividends  \
 Date
 2021-01-01  29.980000  30.000  29.771999  29.900999       0          0
 2021-01-04  29.955999  30.013  29.830000  29.954000       0          0
 2021-01-05  29.920000  29.980  29.830000  29.910000       0          0
 2021-01-06  29.924000  29.980  29.834999  29.920000       0          0
 2021-01-07  29.920000  30.080  29.865000  29.920000       0          0
 2021-01-08  30.059000  30.160  30.018999  30.070000       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  THB=X
 2021-01-04             0  THB=X
 2021-01-05             0  THB=X
 2021-01-06             0  THB=X
 2021-01-07             0  THB=X
 2021-01-08             0  THB=X  ,
                 Open      High       Low     Close  Volume  Dividends  \
 Date
 2021-01-01  14.48120  14.59050  14.37339  14.48120       0          0
 2021-01-04  14.66232  14.74230  14.49600  14.64985       0          0
 2021-01-05  14.71120  15.05500  14.60960  14.67540       0          0
 2021-01-06  14.96240  15.13180  14.87480  14.95030       0          0
 2021-01-07  15.03470  15.46130  14.98880  15.03079       0          0
 2021-01-08  15.42210  15.47949  15.19840  15.41900       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  ZAR=X
 2021-01-04             0  ZAR=X
 2021-01-05             0  ZAR=X
 2021-01-06             0  ZAR=X
 2021-01-07             0  ZAR=X
 2021-01-08             0  ZAR=X  ,
                  Open       High        Low      Close  Volume  Dividends  \
 Date
 2021-01-01  73.911201  73.911201  73.910004  73.911201       0          0
 2021-01-04  74.342598  74.485703  73.042503  74.127403       0          0
 2021-01-05  74.464996  75.172997  73.959099  74.475403       0          0
 2021-01-06  74.213997  74.216301  73.411003  74.135101       0          0
 2021-01-07  74.099998  74.921799  73.540901  74.091499       0          0
 2021-01-08  74.597702  74.806999  73.835999  74.595100       0          0

             Stock Splits   Name
 Date
 2021-01-01             0  RUB=X
 2021-01-04             0  RUB=X
 2021-01-05             0  RUB=X
 2021-01-06             0  RUB=X
 2021-01-07             0  RUB=X
 2021-01-08             0  RUB=X  ]

In [6]:
# Making a for loop for appending all different currency dataframes together 
for i in range(0,len(list_of_values)):
    list_of_values[0] = list_of_values[0].append(list_of_values[i])
list_of_values[0]

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Name
Date,,,,,,,,
2021-01-01,1.217285,1.221699,1.213499,1.218027,0,0,0,EURUSD=X
2021-01-04,1.224905,1.230999,1.217137,1.225070,0,0,0,EURUSD=X
2021-01-05,1.225295,1.229483,1.224995,1.225160,0,0,0,EURUSD=X
2021-01-06,1.229861,1.235025,1.226693,1.230027,0,0,0,EURUSD=X
2021-01-07,1.233776,1.234568,1.224665,1.234111,0,0,0,EURUSD=X
...,...,...,...,...,...,...,...,...
2021-01-04,74.342598,74.485703,73.042503,74.127403,0,0,0,RUB=X
2021-01-05,74.464996,75.172997,73.959099,74.475403,0,0,0,RUB=X
2021-01-06,74.213997,74.216301,73.411003,74.135101,0,0,0,RUB=X
2021-01-07,74.099998,74.921799,73.540901,74.091499,0,0,0,RUB=X
2021-01-08,74.597702,74.806999,73.835999,74.595100,0,0,0,RUB=X

In [7]:
result = list_of_values[0]
result = result[["Name","Close"]] # Taking only columns which has name and close values
result = result.rename(columns={"Close":"Value"}) # Renaming close column to Value
result.to_csv("result.csv")
result

                Name      Value
Date
2021-01-01  EURUSD=X   1.218027
2021-01-04  EURUSD=X   1.225070
2021-01-05  EURUSD=X   1.225160
2021-01-06  EURUSD=X   1.230027
2021-01-07  EURUSD=X   1.234111
...              ...        ...
2021-01-04     RUB=X  74.127403
2021-01-05     RUB=X  74.475403
2021-01-06     RUB=X  74.135101
2021-01-07     RUB=X  74.091499
2021-01-08     RUB=X  74.595100

[102 rows x 2 columns]

In [8]:
df = pd.read_csv("result.csv")
df

           Date      Name      Value
0    2021-01-01  EURUSD=X   1.218027
1    2021-01-04  EURUSD=X   1.225070
2    2021-01-05  EURUSD=X   1.225160
3    2021-01-06  EURUSD=X   1.230027
4    2021-01-07  EURUSD=X   1.234111
..          ...       ...        ...
97   2021-01-04     RUB=X  74.127403
98   2021-01-05     RUB=X  74.475403
99   2021-01-06     RUB=X  74.135101
100  2021-01-07     RUB=X  74.091499
101  2021-01-08     RUB=X  74.595100

[102 rows x 3 columns]